services:
  chrome-pyppeteer:
    image: doubledie/chrome-pyppeteer
    build:
      context: .
      platforms: 
        - linux/amd64
    container_name: chrome-server
    volumes:
      - .:/app
    